image: "inspectorio/python:2.7"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - cache/pip
    - cache/pipenv

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8
    - pytest --cov=base_api_client --junitxml=test_result.xml
    - coverage xml -i

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - demo
    - dev
    - /^v\d+\.\d+\.\d+$/
    - /^v\d+\.\d+\.\d+-rc\.\d+$/
    - /^v\d+\.\d+\.\d+-alpha\.\d+$/
    - /^release-v\d+\.\d+\.\d+$/
    - /^feature\/.*$/
    - /^fix\/.*$/
    - /^chore\/.*$/

.devops: &devops |
  # Inspectorio GitLab pipeline shared libs
  [[ "$TRACE" ]] && set -x
  which curl || ( apt-get update -qq -y && apt-get install -qq -y curl ) || ( apk add --no-cache curl )
  # only bash support 'process substitution'
  # docker dind is alpine based. Use workaround instead
  # source <(curl -s -XGET -H "PRIVATE-TOKEN: ${PIPELINE_AUTH}" "${PIPELINE_SHARED_SCRIPT}")
  curl -s -XGET -H "PRIVATE-TOKEN: ${PIPELINE_AUTH}" "${PIPELINE_SHARED_SCRIPT}" -o pipeline.sh
  source ./pipeline.sh

before_script:
  - *devops
  - ssh_agent

after_script:
  - *devops
  - cleanup
