cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - cache/pip

stages:
  - test

.test:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8
    - pytest

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
    - /^v\d+\.\d+\.\d+-rc\.\d+$/
    - /^v\d+\.\d+\.\d+-alpha\.\d+$/
    - /^release-v\d+\.\d+\.\d+$/
    - /^feature\/.*$/
    - /^fix\/.*$/
    - /^chore\/.*$/

test-2.7:
  extends: .test
  image: 'python:2.7'

test-3.4:
  extends: .test
  image: 'python:3.4'

test-3.5:
  extends: .test
  image: 'python:3.5'

test-3.6:
  extends: .test
  image: 'python:3.6'

test-3.7:
  extends: .test
  image: 'python:3.7'
