image: "python:3"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - cache/pip

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8
    - pytest --cov=acf --junitxml=test_result.xml
    - coverage xml -i

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
    - /^v\d+\.\d+\.\d+-rc\.\d+$/
    - /^v\d+\.\d+\.\d+-alpha\.\d+$/
    - /^release-v\d+\.\d+\.\d+$/
    - /^feature\/.*$/
    - /^fix\/.*$/
    - /^chore\/.*$/
